[project]
name = "ai-powered-intelligent-fraud-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Dhanush Kumar", email = "dk652003@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.124.4",
    "joblib>=1.4.2",
    "pandas>=2.0.3",
    "uvicorn>=0.33.0",
    "xgboost>=2.1.4",
]

[project.scripts]
ai-powered-intelligent-fraud-detection = "ai_powered_intelligent_fraud_detection:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
